### ISSUE TITLE
@types file is missing

### ISSUE THREAD

**Issue by suterma** [dsteinman/ts-color-class#5]
When compiling a dependent project, I get

```
Could not find a declaration file for module 'ts-color-class'. ... implicitly has an 'any' type.
  Try `npm i --save-dev @types/ts-color-class` if it exists or add a new declaration (.d.ts) file containing `declare module 'ts-color-class';`
```

When using with typescript. 

Please add such a file

**Comment by dsteinman** [comment]
Sorry about that.  When I wrote this I didn't even know that file was required :)

I've just republished it as v0.10.0 with a .d.ts file and it seems to work, please give it a try.

**Comment by suterma** [comment]
I just tried today, and it work very well now. Thanks for this quick addition.
